#GitHub username 
owner: griedzx

#你的GitHub repo name 
repo: Upptime


#下边写的时候一定注意代码的缩进，“-” 都在同一个竖线上，“name”和“url”也都在同一个竖线上，层次不齐的代码高几率直接报错
sites:
  - name: Alist
    url: https://alist.daizixi.space
  - name: memos
    url: https://memos.daizixi.space



# A-如果监控控制台页面使用github的默认域名，则使用如下设置。和下边B设置互斥，请二选一
#status-website: 
  #baseUrl: 【/repo name】『/upptime』

# B-如果你的监控控制台页面，打算使用自己所有的域名，则使用如下设置，和上边A设置互斥，请二选一
status-website: 
  cname: upptime/daizixi.space

#自定义状态页面的navbar名称与链接
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name:『Upptime』
  introTitle: 这是使用upptime构建的开源网页状态监控页
  introMessage: 【网页简介】
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
